services:
  alist:
    image: "docker.io/xhofe/alist:latest"
    container_name: alist
    volumes:
      - "$HOME/.var/alist:/opt/alist/data"
    ports:
      - "5244:5244"
      - "5245:5245"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Asia/Shanghai
    restart: unless-stopped
